# Generated by Django 4.2.5 on 2023-12-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
