# Generated by Django 4.2.5 on 2023-12-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_updated_at_note_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update_at',
            new_name='expired_at',
        ),
    ]
